import React from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight,
  Clock3,
  MapPin,
  CheckCircle2,
  Sprout,
  ShieldCheck,
  Wheat,
  Activity,
  CalendarDays,
  Ticket,
  Navigation,
  ChevronRight,
} from "lucide-react";

import { useAuth } from "../context/AuthContext";
import heroFarmerImg from "../assets/images/farmer_hero_field_1787461286978.jpg";

export const Hero: React.FC = () => {
  const {
    t,
    user,
    centers,
    queueTokens,
  } = useAuth();

  /*
   * =========================================================
   * USER'S REGISTERED BLOCK
   * =========================================================
   *
   * The farmer's block comes directly from UserProfile.
   *
   * Example:
   * user.block = "Dhaniakhali"
   *
   * We normalize it so that:
   * "Dhaniakhali"
   * "dhaniakhali"
   * " DHANIAKHALI "
   *
   * are treated as the same block.
   */
  const userBlock = user?.block?.trim().toLowerCase() || "";

  /*
   * =========================================================
   * USER'S ASSIGNED / BLOCK-SPECIFIC MANDI
   * =========================================================
   *
   * Priority:
   *
   * 1. Match the farmer's registered block.
   * 2. If no block match exists, use assignedCenterId.
   *
   * We NEVER use centers[0].
   */
  const blockCenter = userBlock
    ? centers?.find(
        (center) =>
          center.block?.trim().toLowerCase() === userBlock
      )
    : undefined;

  const assignedCenter =
    user?.assignedCenterId
      ? centers?.find(
          (center) =>
            center.id === user.assignedCenterId
        )
      : undefined;

  const userCenter =
    blockCenter || assignedCenter || undefined;

  /*
   * =========================================================
   * USER'S OWN ACTIVE TOKEN
   * =========================================================
   *
   * VERY IMPORTANT:
   *
   * We only look for tokens belonging to the currently
   * logged-in farmer.
   *
   * token.farmerId === user.id
   *
   * This prevents Farmer A from seeing Farmer B's token.
   */
  const farmerToken = user?.id
    ? queueTokens?.find(
        (token) =>
          token.farmerId === user.id &&
          (
            token.status === "waiting" ||
            token.status === "called" ||
            token.status === "processing" ||
            token.status === "next"
          )
      )
    : undefined;

  /*
   * =========================================================
   * TOKEN NUMBER
   * =========================================================
   *
   * This is the ACTUAL token generated by bookNewSlot().
   *
   * No hardcoded token number.
   */
  const tokenNumber =
    farmerToken?.tokenNumber ?? null;

  /*
   * =========================================================
   * CENTER NAME
   * =========================================================
   *
   * If the farmer has booked a slot, use the center stored
   * inside the actual token.
   *
   * Otherwise use the farmer's block-specific center.
   */
  const centerName =
    farmerToken?.centerName ||
    userCenter?.name ||
    "Procurement Centre not assigned";

  /*
   * =========================================================
   * CROP
   * =========================================================
   */
  const cropName =
    farmerToken?.crop ||
    user?.primaryCrop ||
    "Your Crop";

  /*
   * =========================================================
   * TOKEN STATUS
   * =========================================================
   */
  const tokenStatus =
    farmerToken?.status || null;

  /*
   * =========================================================
   * STATUS LABEL
   * =========================================================
   */
  const statusLabel =
    tokenStatus === "called"
      ? "Your turn"
      : tokenStatus === "processing"
      ? "In progress"
      : tokenStatus === "next"
      ? "Next"
      : tokenStatus === "waiting"
      ? "Waiting"
      : "Booked";

  /*
   * =========================================================
   * QUEUE INFORMATION
   * =========================================================
   *
   * Your QueueToken type currently has:
   *
   * estimatedWaitMinutes
   *
   * but does NOT have:
   *
   * peopleAhead
   *
   * So we calculate people ahead from the current center's
   * serving token when possible.
   */
  const peopleAhead =
    farmerToken && userCenter
      ? Math.max(
          farmerToken.tokenNumber -
            userCenter.currentServingToken -
            1,
          0
        )
      : null;

  /*
   * Estimated waiting time comes directly from the token.
   */
  const estimatedWait =
    farmerToken?.estimatedWaitMinutes ?? null;

  /*
   * =========================================================
   * BOOKING DATE / TIME
   * =========================================================
   */
  const bookingDate =
    farmerToken?.date || null;

  const bookingTime =
    farmerToken?.timeWindow ||
    farmerToken?.slotTime ||
    null;

  /*
   * =========================================================
   * ACTIVE TOKEN CHECK
   * =========================================================
   */
  const hasActiveToken =
    Boolean(farmerToken);

  /*
   * =========================================================
   * CENTER STATUS
   * =========================================================
   */
  const centerStatus =
    userCenter?.status || null;

  const centerStatusLabel =
    centerStatus === "Open"
      ? "Active"
      : centerStatus === "Crowded"
      ? "Crowded"
      : centerStatus === "Full"
      ? "Full"
      : centerStatus === "Closed"
      ? "Closed"
      : "Not assigned";

  return (
    <section
      id="hero-section"
      className="
        relative overflow-hidden
        bg-gradient-to-b from-white via-slate-50 to-emerald-50/30
        border-b border-slate-200
      "
    >
      {/* =====================================================
          BACKGROUND DECORATION
      ====================================================== */}

      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div
          className="
            absolute -top-32 -right-32
            h-[420px] w-[420px]
            rounded-full
            bg-emerald-200/30
            blur-3xl
          "
        />

        <div
          className="
            absolute top-1/2 -left-40
            h-[360px] w-[360px]
            rounded-full
            bg-lime-100/30
            blur-3xl
          "
        />

        <div
          className="
            absolute inset-x-0 top-0 h-px
            bg-gradient-to-r
            from-transparent via-emerald-300/50 to-transparent
          "
        />
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div
          className="
            grid grid-cols-1
            items-center
            gap-12
            py-12
            sm:py-16
            lg:grid-cols-12
            lg:gap-10
            lg:py-20
          "
        >
          {/* =====================================================
              LEFT SIDE
          ====================================================== */}

          <div className="lg:col-span-6">

            {/* Live platform badge */}
            <div
              className="
                mb-6 inline-flex items-center gap-2
                rounded-full
                border border-emerald-200
                bg-white/80
                px-3.5 py-2
                text-xs font-bold
                text-emerald-800
                shadow-sm
                backdrop-blur
              "
            >
              <span className="relative flex h-2.5 w-2.5">
                <span
                  className="
                    absolute inline-flex
                    h-full w-full
                    animate-ping
                    rounded-full
                    bg-emerald-400
                    opacity-60
                  "
                />

                <span
                  className="
                    relative inline-flex
                    h-2.5 w-2.5
                    rounded-full
                    bg-emerald-600
                  "
                />
              </span>

              <span>
                {t.heroBadge ||
                  "LIVE PROCUREMENT PLATFORM"}
              </span>
            </div>

            {/* Main heading */}
            <h1
              className="
                max-w-3xl
                text-4xl
                font-extrabold
                leading-[1.08]
                tracking-[-0.035em]
                text-slate-950
                sm:text-5xl
                lg:text-[3.8rem]
              "
            >
              {t.heroHeadline1}

              <span
                className="
                  block
                  bg-gradient-to-r
                  from-emerald-700
                  via-emerald-600
                  to-green-500
                  bg-clip-text
                  text-transparent
                "
              >
                {t.heroHeadline2}
              </span>

              <span className="block text-slate-800">
                {t.heroHeadline3}
              </span>
            </h1>

            {/* Description */}
            <p
              className="
                mt-6
                max-w-xl
                text-base
                leading-7
                text-slate-600
                sm:text-lg
              "
            >
              {t.heroSubheadline}
            </p>

            {/* =================================================
                PRIMARY ACTIONS
            ================================================= */}

            <div
              className="
                mt-8
                flex flex-col
                gap-3
                sm:flex-row
              "
            >
              <Link
                to="/schedule"
                id="hero-cta-find-center"
                className="
                  group
                  inline-flex
                  items-center
                  justify-center
                  gap-2
                  rounded-xl
                  bg-emerald-600
                  px-6 py-3.5
                  text-sm
                  font-bold
                  text-white
                  shadow-lg
                  shadow-emerald-600/20
                  transition-all
                  duration-200
                  hover:-translate-y-0.5
                  hover:bg-emerald-700
                  hover:shadow-xl
                  hover:shadow-emerald-600/25
                  sm:text-base
                "
              >
                <CalendarDays className="h-4.5 w-4.5" />

                <span>
                  {t.heroCtaPrimary ||
                    "Book a Procurement Slot"}
                </span>

                <ArrowRight
                  className="
                    h-4 w-4
                    transition-transform
                    duration-200
                    group-hover:translate-x-1
                  "
                />
              </Link>

              <a
                href="#how-it-works"
                id="hero-cta-how-it-works"
                className="
                  inline-flex
                  items-center
                  justify-center
                  gap-2
                  rounded-xl
                  border border-slate-200
                  bg-white
                  px-6 py-3.5
                  text-sm
                  font-bold
                  text-slate-700
                  shadow-sm
                  transition-all
                  duration-200
                  hover:-translate-y-0.5
                  hover:border-slate-300
                  hover:bg-slate-50
                  sm:text-base
                "
              >
                <Sprout className="h-4.5 w-4.5 text-emerald-600" />

                <span>
                  {t.heroCtaSecondary ||
                    "How KishanSetu Works"}
                </span>
              </a>
            </div>

            {/* =================================================
                TRUST STRIP
            ================================================= */}

            <div
              className="
                mt-8
                grid grid-cols-1
                gap-3
                border-t border-slate-200
                pt-6
                sm:grid-cols-3
              "
            >
              <div className="flex items-center gap-2.5">
                <div
                  className="
                    flex h-8 w-8
                    shrink-0
                    items-center justify-center
                    rounded-lg
                    bg-emerald-50
                  "
                >
                  <ShieldCheck className="h-4 w-4 text-emerald-600" />
                </div>

                <span className="text-xs font-semibold text-slate-600">
                  Verified Procurement
                </span>
              </div>

              <div className="flex items-center gap-2.5">
                <div
                  className="
                    flex h-8 w-8
                    shrink-0
                    items-center justify-center
                    rounded-lg
                    bg-blue-50
                  "
                >
                  <Activity className="h-4 w-4 text-blue-600" />
                </div>

                <span className="text-xs font-semibold text-slate-600">
                  Live Status Tracking
                </span>
              </div>

              <div className="flex items-center gap-2.5">
                <div
                  className="
                    flex h-8 w-8
                    shrink-0
                    items-center justify-center
                    rounded-lg
                    bg-amber-50
                  "
                >
                  <CheckCircle2 className="h-4 w-4 text-amber-600" />
                </div>

                <span className="text-xs font-semibold text-slate-600">
                  Transparent Payments
                </span>
              </div>
            </div>
          </div>

          {/* =====================================================
              RIGHT SIDE
          ====================================================== */}

          <div className="relative lg:col-span-6">

            <div className="relative mx-auto max-w-xl">

              {/* =================================================
                  IMAGE
              ================================================= */}

              <div
                className="
                  relative
                  overflow-hidden
                  rounded-[1.75rem]
                  border border-white
                  bg-slate-900
                  shadow-2xl
                  shadow-slate-900/10
                "
              >
                <div className="aspect-[4/3] sm:aspect-[16/11]">
                  <img
                    src={heroFarmerImg}
                    alt="Farmer using KishanSetu procurement services"
                    className="
                      h-full w-full
                      object-cover
                      transition-transform
                      duration-700
                      hover:scale-[1.02]
                    "
                    referrerPolicy="no-referrer"
                  />
                </div>

                <div
                  className="
                    pointer-events-none
                    absolute inset-0
                    bg-gradient-to-t
                    from-slate-950/70
                    via-slate-950/10
                    to-transparent
                  "
                />

                {/* =================================================
                    IMAGE BOTTOM INFORMATION
                ================================================= */}

                <div
                  className="
                    absolute bottom-0 left-0 right-0
                    p-5 sm:p-6
                  "
                >
                  <div className="flex items-end justify-between gap-4">

                    <div>
                      <div
                        className="
                          mb-1
                          flex items-center gap-1.5
                          text-xs font-semibold
                          text-white/80
                        "
                      >
                        <Navigation className="h-3.5 w-3.5" />

                        <span>
                          {centerName}
                        </span>
                      </div>

                      <h2
                        className="
                          text-xl
                          font-bold
                          tracking-tight
                          text-white
                          sm:text-2xl
                        "
                      >
                        Your procurement journey
                      </h2>
                    </div>

                    <div
                      className="
                        hidden
                        rounded-full
                        border border-white/20
                        bg-white/10
                        px-3 py-1.5
                        text-[10px]
                        font-bold
                        uppercase
                        tracking-wider
                        text-white
                        backdrop-blur
                        sm:block
                      "
                    >
                      KishanSetu
                    </div>
                  </div>
                </div>
              </div>

              {/* =================================================
                  TOKEN CARD
              ================================================= */}

              <div
                className="
                  absolute
                  -bottom-8
                  left-3
                  w-[calc(100%-1.5rem)]
                  max-w-[310px]
                  rounded-2xl
                  border border-slate-200
                  bg-white
                  p-4
                  shadow-xl
                  shadow-slate-900/10
                  sm:-left-7
                  sm:max-w-[330px]
                "
              >

                {hasActiveToken ? (
                  <>
                    <div
                      className="
                        flex
                        items-center
                        justify-between
                        gap-3
                        border-b
                        border-slate-100
                        pb-3
                      "
                    >
                      <div className="flex items-center gap-2.5">
                        <div
                          className="
                            flex h-9 w-9
                            items-center justify-center
                            rounded-xl
                            bg-emerald-50
                          "
                        >
                          <Ticket className="h-4.5 w-4.5 text-emerald-600" />
                        </div>

                        <div>
                          <p
                            className="
                              text-[10px]
                              font-bold
                              uppercase
                              tracking-wider
                              text-slate-400
                            "
                          >
                            Your Token
                          </p>

                          <p className="text-sm font-bold text-slate-900">
                            Live Procurement Pass
                          </p>
                        </div>
                      </div>

                      <span
                        className="
                          rounded-full
                          bg-emerald-50
                          px-2.5 py-1
                          text-[10px]
                          font-bold
                          text-emerald-700
                        "
                      >
                        {statusLabel}
                      </span>
                    </div>

                    <div className="mt-4 flex items-end justify-between">
                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                          Token Number
                        </p>

                        <p className="mt-0.5 text-3xl font-extrabold tracking-tight text-slate-950">
                          #{tokenNumber}
                        </p>
                      </div>

                      <div className="text-right">
                        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                          Crop
                        </p>

                        <div className="mt-1 flex items-center justify-end gap-1.5">
                          <Wheat className="h-3.5 w-3.5 text-emerald-600" />

                          <span className="max-w-[120px] truncate text-sm font-bold text-slate-800">
                            {cropName}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* =================================================
                        QUEUE DETAILS
                    ================================================= */}

                    {(peopleAhead !== null ||
                      estimatedWait !== null) && (
                      <div className="mt-4 grid grid-cols-2 gap-2">

                        {peopleAhead !== null && (
                          <div
                            className="
                              rounded-xl
                              border border-slate-100
                              bg-slate-50
                              p-2.5
                            "
                          >
                            <p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
                              Ahead of you
                            </p>

                            <p className="mt-0.5 text-sm font-bold text-slate-900">
                              {peopleAhead} farmer
                              {peopleAhead === 1
                                ? ""
                                : "s"}
                            </p>
                          </div>
                        )}

                        {estimatedWait !== null && (
                          <div
                            className="
                              rounded-xl
                              border border-slate-100
                              bg-slate-50
                              p-2.5
                            "
                          >
                            <p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
                              Est. wait
                            </p>

                            <p className="mt-0.5 flex items-center gap-1 text-sm font-bold text-emerald-700">
                              <Clock3 className="h-3.5 w-3.5" />

                              {estimatedWait} min
                            </p>
                          </div>
                        )}

                      </div>
                    )}

                    {/* =================================================
                        DATE / TIME
                    ================================================= */}

                    {(bookingDate ||
                      bookingTime) && (
                      <div
                        className="
                          mt-3
                          flex items-center gap-2
                          rounded-xl
                          border border-emerald-100
                          bg-emerald-50/70
                          px-3 py-2.5
                        "
                      >
                        <CalendarDays className="h-4 w-4 text-emerald-600" />

                        <div>
                          <p className="text-[9px] font-bold uppercase tracking-wider text-emerald-600">
                            Scheduled
                          </p>

                          <p className="text-xs font-bold text-slate-800">
                            {bookingDate ||
                              "Scheduled"}{" "}
                            {bookingTime
                              ? `• ${bookingTime}`
                              : ""}
                          </p>
                        </div>
                      </div>
                    )}

                  </>
                ) : (
                  /* =================================================
                     NO TOKEN STATE
                  ================================================= */

                  <>
                    <div className="flex items-center gap-3">
                      <div
                        className="
                          flex h-10 w-10
                          items-center justify-center
                          rounded-xl
                          bg-emerald-50
                        "
                      >
                        <CalendarDays className="h-5 w-5 text-emerald-600" />
                      </div>

                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                          Procurement
                        </p>

                        <p className="text-sm font-bold text-slate-900">
                          No active booking
                        </p>
                      </div>
                    </div>

                    <p className="mt-3 text-xs leading-5 text-slate-500">
                      Book your procurement slot and
                      get a digital token before visiting
                      the centre.
                    </p>

                    <Link
                      to="/schedule"
                      className="
                        mt-3
                        flex items-center justify-between
                        rounded-xl
                        bg-emerald-600
                        px-3.5 py-2.5
                        text-xs font-bold
                        text-white
                        transition
                        hover:bg-emerald-700
                      "
                    >
                      <span>
                        Book your slot
                      </span>

                      <ChevronRight className="h-4 w-4" />
                    </Link>
                  </>
                )}

              </div>

              {/* =================================================
                  CENTER STATUS CARD
              ================================================= */}

              <div
                className="
                  absolute
                  -right-2
                  -top-5
                  max-w-[230px]
                  rounded-2xl
                  border border-white/70
                  bg-white/95
                  p-3.5
                  shadow-xl
                  shadow-slate-900/10
                  backdrop-blur
                  sm:-right-5
                "
              >
                <div className="flex items-center gap-2.5">
                  <div
                    className="
                      flex h-9 w-9
                      items-center justify-center
                      rounded-xl
                      bg-emerald-50
                    "
                  >
                    <MapPin className="h-4.5 w-4.5 text-emerald-600" />
                  </div>

                  <div>
                    <div className="flex items-center gap-1.5">
                      <span className="relative flex h-2 w-2">
                        <span
                          className="
                            absolute
                            h-full w-full
                            animate-ping
                            rounded-full
                            bg-emerald-400
                          "
                        />

                        <span
                          className="
                            relative
                            h-2 w-2
                            rounded-full
                            bg-emerald-600
                          "
                        />
                      </span>

                      <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">
                        {centerStatusLabel}
                      </span>
                    </div>

                    <p className="mt-0.5 max-w-[150px] truncate text-xs font-bold text-slate-800">
                      {centerName}
                    </p>
                  </div>
                </div>

                <div className="mt-3 border-t border-slate-100 pt-2.5">
                  <div className="flex items-center justify-between text-[10px]">
                    <span className="font-medium text-slate-400">
                      {userBlock
                        ? `Block: ${user.block}`
                        : "Registered block"}
                    </span>

                    <span className="font-bold text-emerald-600">
                      {userCenter?.code || "—"}
                    </span>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      {/* =========================================================
          BOTTOM QUICK BENEFITS
      ========================================================== */}

      <div className="relative border-t border-slate-200 bg-white/70">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div
            className="
              grid grid-cols-1
              divide-y divide-slate-200
              py-1
              sm:grid-cols-3
              sm:divide-x
              sm:divide-y-0
            "
          >
            <div className="flex items-center gap-3 px-2 py-4 sm:px-6">
              <div
                className="
                  flex h-9 w-9
                  shrink-0
                  items-center justify-center
                  rounded-lg
                  bg-emerald-50
                "
              >
                <Ticket className="h-4 w-4 text-emerald-600" />
              </div>

              <div>
                <p className="text-xs font-bold text-slate-800">
                  Digital Token
                </p>

                <p className="text-[11px] text-slate-500">
                  Skip unnecessary waiting
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 px-2 py-4 sm:px-6">
              <div
                className="
                  flex h-9 w-9
                  shrink-0
                  items-center justify-center
                  rounded-lg
                  bg-blue-50
                "
              >
                <Activity className="h-4 w-4 text-blue-600" />
              </div>

              <div>
                <p className="text-xs font-bold text-slate-800">
                  Live Queue
                </p>

                <p className="text-[11px] text-slate-500">
                  Know your position in real time
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 px-2 py-4 sm:px-6">
              <div
                className="
                  flex h-9 w-9
                  shrink-0
                  items-center justify-center
                  rounded-lg
                  bg-amber-50
                "
              >
                <CheckCircle2 className="h-4 w-4 text-amber-600" />
              </div>

              <div>
                <p className="text-xs font-bold text-slate-800">
                  Transparent Procurement
                </p>

                <p className="text-[11px] text-slate-500">
                  Track weighing, status & payment
                </p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
  );
};